# Configuration Netlify pour l'application Solvix
# Cette configuration permet de gérer correctement les routes SPA (Single Page Application)

[build]
  publish = "dist"
  command = "npm run build"

# Redirection pour les routes SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# En-têtes de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://*.supabase.co; img-src 'self' data: https://*.supabase.co https://*.pexels.com; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com;"